extends: 'eslint:recommended'
env:
  browser: true
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  no-mixed-spaces-and-tabs:
    - error
    - smart-tabs
  linebreak-style:
    - error
    - unix
  max-len:
    - warn
    - code: 80
      tabWidth: 2
      ignoreUrls: true
  quotes:
    - warn
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  space-before-blocks:
    - warn
    - always
  block-spacing:
    - warn
    - always
  key-spacing:
    - warn
  object-curly-spacing:
    - warn
    - always
  space-infix-ops:
    - warn
  no-unused-vars:
    - warn
    - argsIgnorePattern: '^event$'
  no-console:
    - warn
    - allow:
      - error
      - warn
